### PR TITLE
Add Docker Compose configuration for Memgraph MAGE and Memgraph Lab

### PR DESCRIPTION
**Pull request by kgolubic**
### Description:
This PR introduces a Docker Compose configuration file to simplify the deployment and management of Memgraph and Memgraph Lab within containerized environments. The configuration specifies the use of `memgraph/memgraph-mage` and `memgraph/lab` images, setting up the necessary ports, volumes, and environment variables to ensure seamless integration and quick setup for developers.

#### Key Features:
- **Memgraph Database**: Configured with ports `7687` (Bolt protocol) and `7444` (optional HTTPS interface), along with volumes for data (`mg_lib`), logs (`mg_log`), and configuration (`mg_etc`). The log level is set to `TRACE` for detailed output, aiding in debugging and development.
- **Memgraph Lab**: Set to connect automatically to the Memgraph service using environment variables. It's accessible through port `3000`.
- **Service Dependency**: Ensures that Memgraph Lab starts only after the Memgraph database service is up and running.

#### Notes:
- This configuration is optimized for development and testing environments. For production deployments, consider customizing the configuration to meet security and performance requirements.
- The `--log-level=TRACE` option in Memgraph service provides detailed logging, which can be adjusted as per development needs.

### Testing:
The Docker Compose setup has been tested locally on Windows 11, ensuring that both Memgraph and Memgraph Lab services start correctly and can communicate with each other. Further testing across different environments is recommended to validate the configuration fully.

### Memgraph platform one-liner deployment command
- download and execute shell script:
~`curl -sSf "https://install.memgraph.com" | sh`~
`curl https://install.memgraph.com | sh`
`iwr https://windows.memgraph.com | iex`

### Checks
- [x] installed dependecies (docker, docker compose)
- [x] ~available ports (3000, 7687, 7444)~
- [x] ~already running containers~

### TODO
- [x] write script for unix
- [x] setup domain and webworker on cloudflare
- [x] test
- [x] remove -d flag from docker compose
- [x] make error messages more verbose
  - add requirements message on missing deps
- [x] check iwr
- [x] should we use -sSf flags?

### CODE REVIEW

**Comment by MarkoBarisic** [comment]
I checked if it works on Linux (Ubuntu 22.04), it's working fine.

**Comment by MarkoBarisic** [comment]
I added the container names to make sure the names are hardcoded instead of being dynamically created (<name of root dir>-<name of service>-1)

**Comment by katarinasupe** [comment]
> I added the container names to make sure the names are hardcoded instead of being dynamically created (--1)

Should we name the service memgraph-mage as well?

**Comment by katarinasupe** [comment]
Tested on Mac M1 - works fine.

**Review by tonilastre — APPROVED** [review]
Looks good! Do you plan to remove old memgraph-platform resources such as: supervisord, supervisor configs, etc.

I don't see why we should keep them as they are already in the GH history.

**Comment by MarkoBarisic** [comment]
@tonilastre I agree with you, but what do you think about this? Let's merge this PR as is, then make a PR to restructure the repository in which we will remove deprecated files and folders.

**Comment by tonilastre** [comment]
Yep that sounds good

**Pull request merged**
